---
title: "Map for Elisa"
author: "Joe Brew"
date: "June 7, 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA, message = FALSE, echo = TRUE, results = 'hide', fig.height = 3.5, warning = FALSE)
```

```{r}
# Packages
library(readxl)
library(maps)
library(leaflet)
library(raster)
library(sp)
library(maptools)
library(dplyr)
library(ggmap)

# Define hospital location
hospital <- data.frame(
  name = 'Hospital San Jose',
  stringsAsFactors = FALSE
)
# Geocode hospital location
# temp <- geocode(location = hospital$name)
# hospital$lon <- temp$lon; hospital$lat <- temp$lat
hospital$lat <- 8.1772533
hospital$lon <- -76.0568453


# Read data
df <- read_excel('CODistances33_03_06_2016.xls')
# remove NA first column
df <- df[,2:ncol(df)]
# Get rid of the empty last few rows
df <- df[1:39,]

# Adjust column names
names(df)[3] <- 'ethnic_group'

# Adjust ethnic group
df$ethnic_group <- ifelse(is.na(df$ethnic_group), 'other', df$ethnic_group)

# Create a color column
df$color <-
  ifelse(df$ethnic_group == 'other', 'blue', 
         ifelse(df$ethnic_group == 'Embera Katio ' , 'darkred', 'grey'))
df$color <- adjustcolor(df$color, alpha.f = 0.6)

# Create a 1 2 type for parasite type
df$parasite_type <- 
  ifelse(df$PARASITE == 'P vivax', 1,
         ifelse(df$PARASITE == 'P falciparum', 2,
                NA))

# Get easier to use column names
df$lon <- df$NEWLONGITU
df$lat <- df$NEWLATITUD

# # Get distance 
# for (i in 1:nrow(df)){
#   sub_df <- df[i,]
#   temp <- route(to = c(hospital$lon, hospital$lat),
#                   from = c(sub_df$lon, sub_df$lat),
#                   # mode = 'walking',
#                   output = 'all',
#                   messaging = TRUE)
# }

# Get Columbian shapefile
colombia <- getData('GADM', country = 'COL', level = 2)

# Get a spatial version of df
df_spatial <- data.frame(df)
coordinates(df_spatial) <- ~NEWLONGITU + NEWLATITUD
proj4string(df_spatial) <- proj4string(colombia)

# Get which polygons of th shapefile each point is in
keep_polys <- unique(over(df_spatial, polygons(colombia)))

# Get a smaller spatial object of only the relevant polygons
colombia_sub <- colombia[keep_polys,]
```

# Static map

The below map is a static image. 

```{r}
# Plot
plot(colombia_sub)
points(df$lon, 
       df$lat, 
       col = df$color,
       pch = df$parasite_type, 
       cex = 1)
# # Add lines
# for (i in 1:nrow(df)){
#     sub_df <- df[i,]
#     lines(x = c(sub_df$lon, hospital$lon),
#           y = c(sub_df$lat, hospital$lat),
#           col = sub_df$color)
# }

# Add legend
legend('topleft',
       pch = c(1,2),
       legend = c('P vivax', 'P falciparum'))
legend('topright',
       pch = 1,
       col = c('darkred', 'blue'),
       legend = c('Embera Katio', 'Other'))

```

# Interactive map

The below map is an interactive HTML widget. Zoom in and out, and click on points.

```{r, results = 'show'}
# Leaflet plot
# m <- leaflet(data = colombia_sub)
m <- leaflet() %>% 
  setView(lng = mean(df$lon),
          lat = mean(df$lat),
          zoom = 9)
# m <- m %>% addProviderTiles('Stamen.Watercolor',
#                             options = providerTileOptions(opacity = 0.35))
# m <- m %>% addProviderTiles('MapQuestOpen.Aerial',
#                             options = providerTileOptions(opacity = 1))
m <- m %>% addProviderTiles('Esri.WorldImagery',
                            options = providerTileOptions(opacity = 1))
# m <- m %>% addProviderTiles('Stamen.TonerLite',
#                             options = providerTileOptions(opacity = 0.5))

# Add lines
df_temp <- df %>%
  dplyr::select(lon, lat, ethnic_group, SUBJID) 
hospital_temp <- hospital %>%
          dplyr::select(lon, lat) %>%
  mutate(ethnic_group = NA,
         SUBJID = NA)
results_list <- list()
for (i in 1:nrow(df)){
  new_data <- rbind(hospital_temp,
                    df_temp[i,])
  new_data$group <- i
  new_data$ethnic_group <- df_temp$ethnic_group[i]
  new_data$SUBJID <- df_temp$SUBJID[i]
  results_list[[i]] <- new_data
}
results <- do.call('rbind', results_list)
## Adds indigenous lines
# m <- m %>%
#   addPolylines(data = results %>% filter(ethnic_group == 'Embera Katio '), 
#                lng = ~lon, 
#                lat = ~lat, 
#                group = ~group,
#                popup = ~SUBJID,
#                color = 'darkred',
#                opacity = 0.5,
#                fillOpacity = 0.5)
## Add other lines
# m <- m %>%
#   addPolylines(data = results %>% filter(ethnic_group != 'Embera Katio '), 
#                lng = ~lon, 
#                lat = ~lat, 
#                group = ~group,
#                popup = ~SUBJID,
#                color = 'darkblue',
#                opacity = 0.5,
#                fillOpacity = 0.5)
# Add others
temp <- df %>% filter(ethnic_group != 'Embera Katio ')
m <- m %>% addCircleMarkers(data = temp, 
                            lng = ~lon, 
                            lat = ~lat,
                            radius = temp$parasite_type * 2,
                            popup = ~SUBJID,
                            color = 'darkblue',
                            # opacity = temp$parasite_type -1,
                            opacity = 1,
                            fillOpacity = temp$parasite_type / 2)
# Add indigenous
temp <- df %>% filter(ethnic_group == 'Embera Katio ')
m <- m %>% addCircleMarkers(data = temp, 
                            lng = ~lon, 
                            lat = ~lat,
                            radius = temp$parasite_type * 2,
                            popup = ~SUBJID,
                            color = 'darkred',
                            # opacity = temp$parasite_type -1,
                            opacity = 1,
                            fillOpacity = temp$parasite_type / 2)
# Add hospital
m <- m %>%
  addCircleMarkers(data = hospital,
                   lng = ~lon,
                   lat = ~lat,
                   radius = 1,
                   popup = ~name,
                   opacity = 0.5,
                   fillOpacity = 0.5,
                   color = 'yellow',
                   weight = 1,
                   fill = FALSE)


m 
```